/**
 * Mock for lucide-react icons
 */

import React from 'react';

// Create a mock component factory for all icons
const createMockIcon = (name: string) => {
  const MockIcon = React.forwardRef((props: any, ref: any) => (
    <svg
      {...props}
      ref={ref}
      data-testid={`icon-${name}`}
    >
      <title>{name}</title>
    </svg>
  ));
  MockIcon.displayName = name;
  return MockIcon;
};

// Export all required icons as mock components
export const Play = createMockIcon('Play');
export const Pause = createMockIcon('Pause');
export const RefreshCw = createMockIcon('RefreshCw');
export const AlertCircle = createMockIcon('AlertCircle');
export const CheckCircle = createMockIcon('CheckCircle');
export const Clock = createMockIcon('Clock');
export const Database = createMockIcon('Database');
export const FileSearch = createMockIcon('FileSearch');
export const Activity = createMockIcon('Activity');
export const AlertTriangle = createMockIcon('AlertTriangle');
export const X = createMockIcon('X');
export const ChevronRight = createMockIcon('ChevronRight');
export const ChevronLeft = createMockIcon('ChevronLeft');
export const ChevronDown = createMockIcon('ChevronDown');
export const ChevronUp = createMockIcon('ChevronUp');
export const Home = createMockIcon('Home');
export const Search = createMockIcon('Search');
export const Settings = createMockIcon('Settings');
export const User = createMockIcon('User');
export const LogOut = createMockIcon('LogOut');
export const Menu = createMockIcon('Menu');
export const MoreVertical = createMockIcon('MoreVertical');
export const MoreHorizontal = createMockIcon('MoreHorizontal');
export const Upload = createMockIcon('Upload');
export const Download = createMockIcon('Download');
export const File = createMockIcon('File');
export const Folder = createMockIcon('Folder');
export const FolderOpen = createMockIcon('FolderOpen');
export const Copy = createMockIcon('Copy');
export const Trash = createMockIcon('Trash');
export const Edit = createMockIcon('Edit');
export const Save = createMockIcon('Save');
export const Plus = createMockIcon('Plus');
export const Minus = createMockIcon('Minus');
export const Check = createMockIcon('Check');
export const Info = createMockIcon('Info');
export const Warning = createMockIcon('Warning');
export const Error = createMockIcon('Error');
export const Bell = createMockIcon('Bell');
export const Star = createMockIcon('Star');
export const Heart = createMockIcon('Heart');
export const Share = createMockIcon('Share');
export const Link = createMockIcon('Link');
export const ExternalLink = createMockIcon('ExternalLink');
export const Calendar = createMockIcon('Calendar');
export const MapPin = createMockIcon('MapPin');
export const Phone = createMockIcon('Phone');
export const Mail = createMockIcon('Mail');
export const MessageSquare = createMockIcon('MessageSquare');
export const Image = createMockIcon('Image');
export const Video = createMockIcon('Video');
export const Music = createMockIcon('Music');
export const Mic = createMockIcon('Mic');
export const Camera = createMockIcon('Camera');
export const Zap = createMockIcon('Zap');
export const Shield = createMockIcon('Shield');
export const Lock = createMockIcon('Lock');
export const Unlock = createMockIcon('Unlock');
export const Key = createMockIcon('Key');
export const Eye = createMockIcon('Eye');
export const EyeOff = createMockIcon('EyeOff');
export const Filter = createMockIcon('Filter');
export const SortAsc = createMockIcon('SortAsc');
export const SortDesc = createMockIcon('SortDesc');
export const Globe = createMockIcon('Globe');
export const Wifi = createMockIcon('Wifi');
export const WifiOff = createMockIcon('WifiOff');
export const Cloud = createMockIcon('Cloud');
export const CloudOff = createMockIcon('CloudOff');
export const Sun = createMockIcon('Sun');
export const Moon = createMockIcon('Moon');
export const Loader = createMockIcon('Loader');
export const Loader2 = createMockIcon('Loader2');
export const ArrowRight = createMockIcon('ArrowRight');
export const ArrowLeft = createMockIcon('ArrowLeft');
export const ArrowUp = createMockIcon('ArrowUp');
export const ArrowDown = createMockIcon('ArrowDown');
export const LogIn = createMockIcon('LogIn');
export const UserPlus = createMockIcon('UserPlus');
export const UserMinus = createMockIcon('UserMinus');
export const UserCheck = createMockIcon('UserCheck');
export const UserX = createMockIcon('UserX');
export const Users = createMockIcon('Users');
export const Package = createMockIcon('Package');
export const Package2 = createMockIcon('Package2');
export const Archive = createMockIcon('Archive');
export const Inbox = createMockIcon('Inbox');
export const Send = createMockIcon('Send');
export const PenTool = createMockIcon('PenTool');
export const Tool = createMockIcon('Tool');
export const Wrench = createMockIcon('Wrench');
export const Hammer = createMockIcon('Hammer');
export const Clipboard = createMockIcon('Clipboard');
export const ClipboardCheck = createMockIcon('ClipboardCheck');
export const ClipboardX = createMockIcon('ClipboardX');
export const ClipboardCopy = createMockIcon('ClipboardCopy');
export const ClipboardList = createMockIcon('ClipboardList');
export const FileText = createMockIcon('FileText');
export const FilePlus = createMockIcon('FilePlus');
export const FileMinus = createMockIcon('FileMinus');
export const FileCheck = createMockIcon('FileCheck');
export const FileX = createMockIcon('FileX');
export const Files = createMockIcon('Files');
export const Paperclip = createMockIcon('Paperclip');
export const Printer = createMockIcon('Printer');
export const Code = createMockIcon('Code');
export const Code2 = createMockIcon('Code2');
export const Terminal = createMockIcon('Terminal');
export const GitBranch = createMockIcon('GitBranch');
export const GitCommit = createMockIcon('GitCommit');
export const GitMerge = createMockIcon('GitMerge');
export const GitPullRequest = createMockIcon('GitPullRequest');
export const Github = createMockIcon('Github');
export const Gitlab = createMockIcon('Gitlab');
export const Hash = createMockIcon('Hash');
export const Tag = createMockIcon('Tag');
export const Bookmark = createMockIcon('Bookmark');
export const Award = createMockIcon('Award');
export const Badge = createMockIcon('Badge');
export const Flag = createMockIcon('Flag');
export const Target = createMockIcon('Target');
export const TrendingUp = createMockIcon('TrendingUp');
export const TrendingDown = createMockIcon('TrendingDown');
export const BarChart = createMockIcon('BarChart');
export const BarChart2 = createMockIcon('BarChart2');
export const LineChart = createMockIcon('LineChart');
export const PieChart = createMockIcon('PieChart');
export const DollarSign = createMockIcon('DollarSign');
export const CreditCard = createMockIcon('CreditCard');
export const ShoppingCart = createMockIcon('ShoppingCart');
export const ShoppingBag = createMockIcon('ShoppingBag');
export const Gift = createMockIcon('Gift');
export const Coffee = createMockIcon('Coffee');
export const Compass = createMockIcon('Compass');
export const Map = createMockIcon('Map');
export const Navigation = createMockIcon('Navigation');
export const Navigation2 = createMockIcon('Navigation2');
export const Crosshair = createMockIcon('Crosshair');
export const Layers = createMockIcon('Layers');
export const Grid = createMockIcon('Grid');
export const List = createMockIcon('List');
export const AlignLeft = createMockIcon('AlignLeft');
export const AlignCenter = createMockIcon('AlignCenter');
export const AlignRight = createMockIcon('AlignRight');
export const AlignJustify = createMockIcon('AlignJustify');
export const Bold = createMockIcon('Bold');
export const Italic = createMockIcon('Italic');
export const Underline = createMockIcon('Underline');
export const Type = createMockIcon('Type');
export const Scissors = createMockIcon('Scissors');
export const MinusCircle = createMockIcon('MinusCircle');
export const PlusCircle = createMockIcon('PlusCircle');
export const HelpCircle = createMockIcon('HelpCircle');
export const InfoCircle = createMockIcon('InfoCircle');
export const XCircle = createMockIcon('XCircle');
export const Trash2 = createMockIcon('Trash2');
export const Move = createMockIcon('Move');
export const Maximize = createMockIcon('Maximize');
export const Maximize2 = createMockIcon('Maximize2');
export const Minimize = createMockIcon('Minimize');
export const Minimize2 = createMockIcon('Minimize2');
export const Expand = createMockIcon('Expand');
export const Shrink = createMockIcon('Shrink');
export const Square = createMockIcon('Square');
export const Circle = createMockIcon('Circle');
export const Triangle = createMockIcon('Triangle');
export const Hexagon = createMockIcon('Hexagon');
export const Octagon = createMockIcon('Octagon');
export const BookOpen = createMockIcon('BookOpen');
export const Book = createMockIcon('Book');
export const BookMarked = createMockIcon('BookMarked');